## persistence section
spring:
  datasource:
    url: jdbc:h2:mem:batch
    #url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres

    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000 #timeout in ms

  flyway:
    locations: classpath:db/migration

  batch:
    job:
      enabled: false

    #disable creation of BATCH_JOB tables to let flyway do the work
    initialize-schema: never
    table-prefix: catalogs.BATCH_ #prefix that saves the batch tables to the same schema as the catalogs, we could also use a totally seperated schema like "BATCH"