## persistence section
spring:
  datasource:
    #url: jdbc:h2:mem:catalogs
    url: jdbc:postgresql://localhost:5432/catalogs
    username: postgres
    password: postgres

    hikari:
      maximum-pool-size: 10
      connection-timeout: 10000 #timeout in ms

  flyway:
    locations: classpath:db/migration