version: '3.1'
services:
  spring-batch:
    container_name: spring-batch
    image: goafabric/spring-boot-examplebatch${ARCH_SUFFIX}:1.0.1-SNAPSHOT
    environment:
      - TZ=Europe/Berlin
      - spring.datasource.url=jdbc:postgresql://batch-postgres:5432/customer
      - spring.datasource.username=example-batch
      - spring.datasource.password=example-batch
      - spring.batch.rate=500
    entrypoint: ["java","-Xms${SERVICE_MEM}","-Xmx${SERVICE_MEM}",
                 "-Djava.security.egd=file:/dev/./urandom","-cp","/app/resources:/app/classes:/app/libs/*",
                 "org.goafabric.spring.boot.examplebatch.Application"]

    depends_on:
      - batch-postgres

  batch-postgres:
    container_name: batch-postgres
    image: postgres:13.2
    restart: 'no'
    ports:
      - 50810:5432
    environment:
      - TZ=Europe/Berlin
      - POSTGRES_USER=example-batch
      - POSTGRES_PASSWORD=example-batch
      - POSTGRES_DB=customer
    command: postgres -c 'shared_buffers=128MB' -c 'max_connections=30' -c 'shared_preload_libraries=pg_stat_statements'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  tmp:
  applogs:
  pgdata: